version: 0.2

phases:
  install:
      runtime-versions:
        nodejs: 14
      commands:
        - echo Installing
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: ./